### ISSUE TITLE
with --profile, error: invalid argument '-std=c++11' not allowed with 'C'

### ISSUE THREAD

**Issue by gaze** [fpco/inline-c#102]
Hey all, I have an lts-14.11 stack project that builds just fine when invoking ```stack build```, but when building using ```stack build --profile```, I get the following output

```
$ stack build --profile
inline-c-cpp-0.3.0.2: configure
inline-c-cpp-0.3.0.2: build
Progress 1/2

--  While building package inline-c-cpp-0.3.0.2 using:
      /Users/gaze/.stack/setup-exe-cache/x86_64-osx/Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.5 --builddir=.stack-work/dist/x86_64-osx/Cabal-2.4.0.1 build --ghc-options " -ddump-hi -ddump-to-file -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
    Logs have been written to: /Users/gaze/my/nestor-hs/nestor/.stack-work/logs/inline-c-cpp-0.3.0.2.log

    Configuring inline-c-cpp-0.3.0.2...
    Preprocessing library for inline-c-cpp-0.3.0.2..
    Building library for inline-c-cpp-0.3.0.2..
    [1 of 2] Compiling Language.C.Inline.Cpp ( src/Language/C/Inline/Cpp.hs, .stack-work/dist/x86_64-osx/Cabal-2.4.0.1/build/Language/C/Inline/Cpp.o )
    [2 of 2] Compiling Language.C.Inline.Cpp.Exceptions ( src/Language/C/Inline/Cpp/Exceptions.hs, .stack-work/dist/x86_64-osx/Cabal-2.4.0.1/build/Language/C/Inline/Cpp/Exceptions.o )
    [1 of 2] Compiling Language.C.Inline.Cpp ( src/Language/C/Inline/Cpp.hs, .stack-work/dist/x86_64-osx/Cabal-2.4.0.1/build/Language/C/Inline/Cpp.p_o )
    error: invalid argument '-std=c++11' not allowed with 'C'
    `clang++' failed in phase `C Compiler'. (Exit code: 1)
```

This is under macOS 10.14.4. It's repeatable when deleting ~/.stack and/or .stack-work and then running build or build --profile in either order.

**Comment by bitonic** [comment]
Thanks for the report. It looks like a clang-specific issue. However, I can't easily reproduce because of https://github.com/commercialhaskell/stack/issues/4073 . I might just try on the macbook later, but in the meantime, can you post a fully verbose build here? Maybe I can offer some guidance then.

**Comment by gaze** [comment]
Here's stack ```build --profile --verbose```

[dump.txt](https://github.com/fpco/inline-c/files/3751597/dump.txt)

**Comment by bitonic** [comment]
@gaze sadly that does not include the `ghc` invocation, and the invocation itself is not verbose. I think `--cabal-verbose --ghc-options=-v` should do it.

**Comment by gaze** [comment]
Apologies! Still a bit new to Haskell.

```stack build --profile --verbose --cabal-verbose --ghc-options=-v 2> dump2.txt```
[dump2.txt](https://github.com/fpco/inline-c/files/3751652/dump2.txt)

**Comment by gaze** [comment]
Fwiw, this allowed me to build. Not sure what the interaction would be with other platforms

```
diff --git a/inline-c-cpp/inline-c-cpp.cabal b/inline-c-cpp/inline-c-cpp.cabal
index 7985158..2e9ad42 100644
--- a/inline-c-cpp/inline-c-cpp.cabal
+++ b/inline-c-cpp/inline-c-cpp.cabal
@@ -26,7 +26,7 @@ library
                      , safe-exceptions
   hs-source-dirs:      src
   default-language:    Haskell2010
-  ghc-options:         -Wall -optc-std=c++11
+  ghc-options:         -Wall -optc-xc++
   if os(darwin)
     -- avoid https://gitlab.haskell.org/ghc/ghc/issues/11829
     ld-options:        -Wl,-keep_dwarf_unwind
```

**Comment by bitonic** [comment]
@gaze thank you, `-optc-x-c++` makes a lot of sense, but I do not know why it'd break only with `--profile`. Anyway, I've created https://github.com/fpco/inline-c/pull/103 to fix this problem in the repo.

**Comment by bitonic** [comment]
@gaze I've added `-x-c++` to `inline-c-cpp.cabal`, and uploaded new inline-c-cpp version 0.3.0.3.

**Comment by tscholak** [comment]
seems this issue is back with ghc 8.10.3. has anybody else run into this again recently?
