### ISSUE TITLE
Templates with pointers breaks the compiler

### ISSUE THREAD

**Issue by Ofenhed** [fpco/inline-c#113]
It seems that any pointer in a template definition breaks compilation.

For reference, here's a test that breaks compilation:

```
    Hspec.it "Template with pointers" $ do
      pt <- [C.block| std::vector<int*>* {
          return new std::vector<int*>();
        } |] :: IO (Ptr (StdVector.CStdVector (Ptr C.CInt)))
      [C.block| void {
          int *a = new int;
          *a = 100;
          $(std::vector<int*>* pt)->push_back(a);
          std::cout << *((*$(std::vector<int*>* pt))[0]) << std::endl;
        } |]
```

**Comment by bitonic** [comment]
@junjihashimoto , could you take a look at this?

**Comment by Ofenhed** [comment]
Digging around in the code shows that a template can only have `TypeSpecifier`s and numbers as argument. From what I can gather from the code, it seems that pointers (even more so if they are volatile), arrays, consts, long longs and chars with specified sign are examples of types which cannot be used. I was going to take a stab at it, but this looks as if it might need a bigger patch than I'd be comfortable submitting.

**Comment by junjihashimoto** [comment]
@bitonic @Ofenhed 
I'm sorry I didn't notice immediately.
https://github.com/fpco/inline-c/blob/master/inline-c/src/Language/C/Types/Parse.hs#L641-L783
It seems that pointers cannot be used grammatically. This was not intended.
C++ often uses smart pointers instead of raw pointers, so I'm not in trouble at all.

**Comment by junjihashimoto** [comment]
https://github.com/fpco/inline-c/pull/114
It is an incomplete support, but `std::vector<int*>` is supported.

**Comment by bitonic** [comment]
@junjihashimoto thanks.

@Ofenhed can you try current master and see if things work for you?

**Comment by Ofenhed** [comment]
Thank you. Yes, it works for my use case. For now I guess the unsupported types can be reached using a typedef.
