### ISSUE TITLE
`Language.C.Inline.Interruptible.block` produces an `unsafe` FFI call

### ISSUE THREAD

**Issue by Jasagredo** [fpco/inline-c#137]
[The QuasiQuoter](https://github.com/fpco/inline-c/blob/master/inline-c/src/Language/C/Inline/Interruptible.hs#L52) is creating an `Unsafe` declaration:

```
block :: TH.QuasiQuoter
block = genericQuote IO $ inlineItems TH.Unsafe False Nothing
```

It should either create an `interruptible` call or if this is intentional might deserve a comment explaining why.

**Comment by bitonic** [comment]
You're absolutely right, this is a bug. I'll fix later today.
