### ISSUE TITLE
$bs-ptr uses unsigned char* by default

### ISSUE THREAD

**Issue by jargv** [fpco/inline-c#16]
In my experience `unsigned char*` is very rare in C code, at least when working with strings. Is there a good reason for unsigned being the default? Is there an easy way to change this behavior (perhaps for a single context) to `char*`?

**Comment by jargv** [comment]
Actually an entire context is probably too course-grained. Is there a way to make it a *signed* `char*` at a single call site?

**Comment by bitonic** [comment]
No, there isn't a way right now.  It would be very easy to add a `Context` doing that, or alternatively a context that took a type explicitely, e.g.

```
$bs-ctx:(char *foo)
```

You're right though, we should support this.

**Comment by bitonic** [comment]
Actually, straight `char` just makes more sense.  I'll change the behaviour of `bs-ctx`.

**Comment by jargv** [comment]
Thanks! The workaround I had landed on is to cast: `(char*)$bs-ptr:title` but that makes me quite nervous since the cast loses a measure of type safety. 

It might be convenient to have a `bs-uptr` for the cases where you actually are dealing with bytes of (unsigned) raw byte data.

**Comment by bitonic** [comment]
Right, that was my original reasoning -- morally `ByteString`s in Haskell are blobs of raw data.

However, I remembered that `ByteString`s contain pointers to straight `char`s, so that's definitely the option that makes more sense.

I'll upload a new version on Hackage soon.
