### ISSUE TITLE
Handle more types by default

### ISSUE THREAD

**Issue by Deewiant** [fpco/inline-c#17]
`Foreign.C.Types` contains a bunch of types that aren't in `baseTypesTable`:

* `CPtrDiff`
* `CSize`
* `CWchar`
* `CSigAtomic`
* `CIntPtr`
* `CUIntPtr`
* `CIntMax`
* `CUIntMax`
* `CClock`
* `CTime`
* `CUSeconds`
* `CSUSeconds`
* `CFile`
* `CFpos`
* `CJmpBuf`

I don't see why they couldn't be added. Furthermore there are the exact-size types in `stdint.h`, like `int32_t`, that could easily be mapped to the types in `Data.Int` and `Data.Word`. (Handling the others like `int_fast8_t`etc. might require more magic than what inline-c currently does, since you can't know in advance which Haskell type they map to.)

**Comment by bitonic** [comment]
Yes, everything in `Foreign.C.Types` and `stdint.h` should be included.  A PR would be appreciated, or I'll do it when I have a bit of time.

**Comment by Deewiant** [comment]
Great, thanks for the quick response. I'll try to get a PR done tonight (within 8 hours or so).
