### ISSUE TITLE
"stale ModuleState" with multiple modules and ghc -j

### ISSUE THREAD

**Issue by Deewiant** [fpco/inline-c#22]
Consider the following simple project:

testcase.cabal:
```
name: testcase
version: 0
build-type: Simple
cabal-version: >=1.10
executable Main
  default-language: Haskell2010
  main-is: Main.hs
  c-sources: One.c, Two.c
  build-depends: base, inline-c
```
One.hs:
```haskell
{-# LANGUAGE QuasiQuotes #-}
module One where
import qualified Language.C.Inline as C
x = [C.exp| int{ 1 } |]
```
Two.hs:
```haskell
{-# LANGUAGE QuasiQuotes #-}
module Two where
import qualified Language.C.Inline as C
y = [C.exp| int{ 2 } |]
```
Main.hs:
```haskell
import One
import Two
main = do a <- x; b <- y; print (a, b)
```

A typical build with `ghc -j1` might look like the following, and works fine:
```
$ cabal clean && cabal build --ghc-options=-j1
cleaning...
Package has never been configured. Configuring with default flags. If this
fails, please run configure manually.
Resolving dependencies...
Configuring testcase-0...
Building testcase-0...
Preprocessing executable 'Main' for testcase-0...
[1 of 3] Compiling Two              ( Two.hs, dist/build/Main/Main-tmp/Two.dyn_o )
[2 of 3] Compiling One              ( One.hs, dist/build/Main/Main-tmp/One.dyn_o )
[3 of 3] Compiling Main             ( Main.hs, dist/build/Main/Main-tmp/Main.dyn_o )
Linking dist/build/Main/Main ...
```

But with `ghc -j`, this tends to happen:
```
$ cabal clean && cabal build --ghc-options=-j
cleaning...
Package has never been configured. Configuring with default flags. If this
fails, please run configure manually.
Resolving dependencies...
Configuring testcase-0...
Building testcase-0...
Preprocessing executable 'Main' for testcase-0...
[1 of 3] Compiling Two              ( Two.hs, dist/build/Main/Main-tmp/Two.dyn_o )
[2 of 3] Compiling One              ( One.hs, dist/build/Main/Main-tmp/One.dyn_o )

One.hs:4:5:
    Exception when trying to run compile-time code:
      inline-c: stale ModuleState
    Code: template-haskell-2.10.0.0:Language.Haskell.TH.Quote.quoteExp
            C.exp " int{ 1 } "
```

Or an equivalent failure in the other module:
```
$ cabal clean && cabal build --ghc-options=-j
cleaning...
Package has never been configured. Configuring with default flags. If this
fails, please run configure manually.
Resolving dependencies...
Configuring testcase-0...
Building testcase-0...
Preprocessing executable 'Main' for testcase-0...
[1 of 3] Compiling Two              ( Two.hs, dist/build/Main/Main-tmp/Two.dyn_o )

Two.hs:4:5:
    Exception when trying to run compile-time code:
      inline-c: stale ModuleState
    Code: template-haskell-2.10.0.0:Language.Haskell.TH.Quote.quoteExp
            C.exp " int{ 2 } "
[2 of 3] Compiling One              ( One.hs, dist/build/Main/Main-tmp/One.dyn_o )
```

I've also seen this manifest as parse errors that seemed like not recognizing custom types added to `ctxTypesTable` (aside: a nicer error message than "expecting type name, got identifier" would go a long way), which makes sense if different modules are overriding each other's state.

In case it matters, this is with GHC 7.10.1.

**Comment by bitonic** [comment]
That makes sense -- I'm using a global `IORef` to store the necessary information, and I had not considered the possibility of parallel builds.

This is definitely fixable, I'll look into it as soon as I can.

**Comment by bitonic** [comment]
I have pushed a fix for this in the `issue-22` branch.  I didn't get to test it properly, I'd be glad if you could run it on your test case in the meantime.  I'll probably get around to test it myself tomorrow.

**Comment by Deewiant** [comment]
Seems to do the trick for both this testcase and the actual project in which I was running into this, thanks!

**Comment by bitonic** [comment]
Could you upload a tarball with a sample project to try out?  That would save me a bit of time.

**Comment by Deewiant** [comment]
I could tarball the "testcase" project in the issue description but that'd probably take longer than it takes you to copy-paste the four files.

My actual project depends on so many esoteric libraries that I can practically guarantee that getting it to compile at all would take you longer than the time you are trying to save... Plus there are some licensing issues I haven't got around to sorting out so I shouldn't be distributing it anyway.

**Comment by bitonic** [comment]
Merged.  Currently waiting the Travis-CI build to finish and I'll upload it to hackage.  Thanks a lot for reporting!
