### ISSUE TITLE
Can't use Haskell variables with primes

### ISSUE THREAD

**Issue by chpatrick** [fpco/inline-c#23]
src/Clang/FFI.hs:181:5:
    Exception when trying to run compile-time code:
      "src/Clang/FFI.hs" (line 181, column 71):
unexpected "'"
expecting digit, "[", "(" or ")"
    Code: Language.Haskell.TH.Quote.quoteExp
            C.exp
            " int { clang_equalCursors(*$(CXCursor *cp), *$(CXCursor *cp')) } "

**Comment by bitonic** [comment]
This is a tricky one: we want to use C-style declarations for anti-quoting, C-style identifiers don't have primes in them.

I have a YACC grammar which I modified from the C standard (that I hand-converted to a `parsers` parser), I'll check if we can change the identifier style without messing up the rest of the grammar.

**Comment by bitonic** [comment]
I've fixed this on `issue-23`.  Can you please verify, just in case I missed something?

(as a bonus, now you can anti-quote any Haskell identifier, even qualified names).
