### ISSUE TITLE
`cabal sdist` contains the generated C files

### ISSUE THREAD

**Issue by bitonic** [fpco/inline-c#29]
Currently, we put the C files generated by `inline-c` in the `c-sources` field in `.cabal` files.  This means that the generated files end up in the tarballs, which does not make sense.  I can't think of a simple way of avoiding this, if we want to keep abusing `cabal` to compile the C sources.

**Comment by mboes** [comment]
See #30 for a wider discussion. Of relevance here: `cabal sdist` does sometimes include generated files, so I think we should close this issue.

**Comment by bitonic** [comment]
The cases where they are included seem to be when the source can then be compiled again without being pre-processed, which is not the case here.  Besides, even if this is happening already, I don't think it's the right thing to do.

**Comment by ekmett** [comment]
Would a custom Setup.hs that added them only in certain cabal steps be the ultimate right answer? Alternately, the cabal sdist hook could remove them if there was an associated haskell source file?

**Comment by bitonic** [comment]
@ekmett , I quickly looked at the facilities provided by `Default.Simple`  in the `Cabal` library and couldn't find an easy way to do that. Did you have something specific in mind?

**Comment by ekmett** [comment]
Not off hand.

**Comment by ekmett** [comment]
What about something like...

```haskell
import Distribution.Simple (defaultMainWithHooks, UserHooks(..), simpleUserHooks)
import Distribution.Simple.LocalBuildInfo (LocalBuildInfo(..))
import Distribution.PackageDescription (BuildInfo(..), Library(..))

extraCSources :: [FilePath]
extraCSources = []

main = defaultMainWithHooks simpleUserHooks
  { preConf = \a cf -> do
    (l,es) <- preConf simpleUserHooks a cf
    return (Just mempty { cSources = extraCSources } `mappend` l, es)
  }
```

This is entirely untested, just the first thing that came to mind.

**Comment by ekmett** [comment]
That should in theory hack them into the `BuildInfo` for the library right before configuration. To do the other executables, you'd have to modify `es` appropriately.

**Comment by bitonic** [comment]
@ekmett , thanks.

I'm wondering how best to do this -- I've never used a `Setup.hs` that was not `defaultSimple`.

Is the best way to do this to provide a function ourself to use as `main` in `Setup.hs`?

Maybe we could also automatically check which C files are to be generated and add them.

**Comment by mboes** [comment]
Recent versions of Cabal allow Setup.hs to depend on packages. So you can provide such a default `main` function in `inline-c` so that users don't need to copy/paste (and get the benefit of bug fixes in the future for free).

See https://github.com/haskell/cabal/pull/2515.

Stack has a way of emulating this: https://github.com/commercialhaskell/stack/blob/master/doc/yaml_configuration.md#explicit-setup-deps.

**Comment by bitonic** [comment]
this is not true anymore since we use `addForeignFile`
