### ISSUE TITLE
`safe` or `interruptible` foreign calls?

### ISSUE THREAD

**Issue by mitchellwrosen** [fpco/inline-c#36]
Is it possible to mark calls as safe/interruptible, like with the traditional Haskell FFI? Having a (extremely brief) look over the code, it seems that "unsafe" is the safety level used everywhere, and it's not configurable.

**Comment by bitonic** [comment]
All calls are marked as `safe`, unless the `Language.C.Inline.Unsafe` module is used.

**Comment by mitchellwrosen** [comment]
I see. So there is no support for `interruptible` calls? Would you accept a PR that adds this support?

**Comment by bitonic** [comment]
Oh, I was not aware of the `interruptible` calls.

Yes, I'd very much appreciate a PR adding that!
