### ISSUE TITLE
Undefined reference to inline_c_Main

### ISSUE THREAD

**Issue by yann-ledu** [fpco/inline-c#40]
Hello,

I have ghc 7.10.2, used cabal to install inline-c, then copy/pasted inside a Main.hs the first example of how to use inline-c and did:

ghc -c Main.hs
cc -c Main.c -o Main_c.o
ghc Main.o -lm -o Main

and the last step gives me:

Main.o: In function `raz7_info':
(.text+0x26): undefined reference to `inline_c_Main_0_2f88ee80765ab54834856cc58acd770f9760d5e4'
collect2: error: ld returned 1 exit status

Any idea how to solve that ?

**Comment by bitonic** [comment]
You're forgetting to include the `Main_c.o` object file when linking.

It should be

```
ghc Main.o Main_c.o -lm -o Main
```

**Comment by yann-ledu** [comment]
Great, thanks.
