### ISSUE TITLE
Behaviour on anti-quoting same identifier multiple times

### ISSUE THREAD

**Issue by lspitzner** [fpco/inline-c#41]
e.g. `return $(int foo) + $(int foo);` creates two parameters. It would be nice if

1) This was clearly documented (I find it hard to infer that specific from "For each anti-quotation, a variable with a matching type is expected in the Haskell environment."); or
2) It did not happen at all, i.e. same-identifiers are merged into one parameter. Might be necessary
to check that types match exactly (`const`ness might cause problems). I have no idea how much hassle that would be to implement.

inline-c-0.5.5.1

---

Apart from that: Very useful package, thanks for your work.

**Comment by bitonic** [comment]
The "one parameter per anti-quotation" was intentional, for the sake of simplicity, since you can easily achieve the same effect using

```
int a = $(int foo)
```

I'll document this behavior.

**Comment by lspitzner** [comment]
Thanks!
