### ISSUE TITLE
Documentation: readme specified different type for bytestring pointer

### ISSUE THREAD

**Issue by expipiplus1** [fpco/inline-c#42]
The readme says that `bs-ptr` is always of type `unsigned char*` however the code specifies `const char*`.

**Comment by bitonic** [comment]
Thanks!

**Comment by expipiplus1** [comment]
Just out of interest, why was it changed from `unsigned char*` to `char*`?

**Comment by bitonic** [comment]
Because for strings, `char *` is more idiomatic in C. See https://github.com/fpco/inline-c/issues/16
