### ISSUE TITLE
Document the lifetime of FunPtrs created by funCtx's antiquoter

### ISSUE THREAD

**Issue by Deewiant** [fpco/inline-c#48]
I just got bit by this for the nth time... `funCtx`'s antiquoter (`fun`) frees the function pointer after the enclosing C code has been run to completion. This probably can't be helped due to the way `FunPtr` lifetimes have to be manually managed, but at least a mention in the documentation would be nice.

In practice, when faced with segfaults or internal errors originating in RTS functions with names like `stg_ap_p_info` and `stg_ap_p_ret` I'm not sure how many people will realize to look at the documentation of `funCtx`, so even a loud warning might not be very helpful but it may be the best we can do.

**Comment by bitonic** [comment]
Good point, I'll get to it soon.

**Comment by bitonic** [comment]
Fixed by c67ce167c514a090bdf470f3927fe487e036668f
