### ISSUE TITLE
REPL/intero support

### ISSUE THREAD

**Issue by proger** [fpco/inline-c#52]
It seems possible use inline-c code in stack ghci / intero once you've built the C counterpart with `stack build` and then loaded the corresponding Haskell module in the repl — however edits cause  errors like:

```
> my_fun_that_uses_c_inline
intero: panic! (the 'impossible' happened)
  (GHC version 8.0.1 for x86_64-apple-darwin):
    Loading temp shared object failed: dlopen(/var/folders/bw/nyfq8tn93ylfck11w4qhx55c0000gn/T/ghc21491_0/libghc_11.dylib, 5): Symbol not found: _inline_c_Image_C_0_87811c198a1652c85336f14e66165c4668b158de
  Referenced from: /var/folders/bw/nyfq8tn93ylfck11w4qhx55c0000gn/T/ghc21491_0/libghc_11.dylib
  Expected in: flat namespace
 in /var/folders/bw/nyfq8tn93ylfck11w4qhx55c0000gn/T/ghc21491_0/libghc_11.dylib

Please report this as a GHC bug:  http://www.haskell.org/ghc/reportabug
```

Which can be worked around by:

``` bash
stack build # build the thing again
# convert the (new) object file into a dynamic lib
ld -dylib -macosx_version_min 10.12 -o thing.dylib ./.stack-work/dist/x86_64-osx/Cabal-1.24.0.0/build/pixels/pixels-tmp/src/Image/C.o
# in ghci:
> :r
> import System.Posix.DynamicLinker
> dlopen "thing.dylib" [RTLD_NOW, RTLD_GLOBAL]
> my_fun_that_uses_c_inline
```

I would love any hints on how to properly automate this. PS thanks @bitonic for the opencv talk, I quite enjoyed it

**Comment by bitonic** [comment]
To support, we'd have to make it so that ghci can build the dynamic library it expects after it has finished type checking all the modules required. This would involve a non-trivial amount of engineering simply because ghci does not support customization at that level -- or at least I think it doesn't. I'm very open to ideas though.

Very glad you enjoyed the talk!

**Comment by proger** [comment]
Does it make sense to hack this through intero? It looks like intero wants to run `stack build` (through elisp, https://github.com/commercialhaskell/intero/issues/146), and to handle non-hs source files (https://github.com/commercialhaskell/intero/issues/80), which is somewhat overlapping with this issue.
I'm thinking of intero mainly because it "knows" about stack projects while ghci technically shouldn't care (I guess ghci could expose a primitive like `:unsafedlopen` for .o files though)

**Comment by bitonic** [comment]
Sadly I know very little about intero, but since it reimplements large parts of what GHCi implements, it might very well be possible to have it do what we want!

I'd be very glad to review whatever patch comes my way in that direction.

**Comment by chrisdone** [comment]
Intero could possibly run those steps (`import System.Posix.DynamicLinker`, `dlopen "thing.dylib" [RTLD_NOW, RTLD_GLOBAL]`).

`stack ghci` could possibly be coached into running `ld -dylib -macosx_version_min 10.12 -o thing.dylib ./.stack-work/dist/x86_64-osx/Cabal-1.24.0.0/build/pixels/pixels-tmp/src/Image/C.o`

The question would be how to tell `stack ghci` and `intero` that this step needs to be run, and how to get the details to do so. Some straw man:

We could run this in `intero` to tell it to relink `thing.dylib` every time a module loading command is complete:

```
:set -dynamic-libs thing.dylib
```

The `stack ghci` command could have this either in the `.cabal` (which would yield warnings):

    ghci-options: -dynamic-libs thing.dylib

Or in the `stack.yaml`:

    ghci-dynamic-libs:
    - thing.dylib

Regarding how to build the `.dylib`, I'm not sure. Intero could do it after a load command, but we need to know all the `.o` files, and when they're updated.

Maybe we make it more abstract and say "module Foo.X produces a .o file which needs ld'ing and dlopen'ing, so sort that out, Intero." and we put that either in a `:dynamic-modules +Foo.X` or so, or in `stack.yaml`.

**Comment by bitonic** [comment]
This will work once https://phabricator.haskell.org/D3280 lands which will make ghci work, provided it uses `-fobject-code`.

**Comment by bitonic** [comment]
Closing since `-fobject-code` works well.
