### ISSUE TITLE
Antiquoted C variables Within C/C++ Comments Are Still Parsed

### ISSUE THREAD

**Issue by georgewsinger** [fpco/inline-c#54]
Small bug. Consider:

```haskell
f n = ...
	where function = (\i -> [C.block| int { 
           //...commented out C code involving $(Type* t)
           return 1; } |])
```

This will cause the compiler to complain that "Variable not in scope: t".

**Comment by bitonic** [comment]
This is undesirable but intended behavior: we do not parse the the C code at all, which means that we cannot know if we're in a comment.
