### ISSUE TITLE
Stack rebuild all  C/C++ sources

### ISSUE THREAD

**Issue by McbearHolden** [fpco/inline-c#80]
I have quite some C/C++ files in the cbits directory. I use stack tool chain for the build process(A project folder created by `stack new myproject`). When I do `stack build` everytime it rebuilds everything, even though nothing changes to those files. How can I save build time?

**Comment by bitonic** [comment]
@McbearHolden I'm not sure, but as far as I can tell this is a stack / cabal issue rather than an inline-c issue.
