### ISSUE TITLE
Using Inline-C in Interpreted Mode (for interactive GHCi debugging).

### ISSUE THREAD

**Issue by georgewsinger** [fpco/inline-c#86]
> Currently inline-c does not work in interpreted mode

AFAIK: this makes it impossible to use the interactive GHCi debugger (correct?).  Is there anything in principle stopping inline-C from being used interactively?

**Comment by bitonic** [comment]
see https://mazzo.li/posts/new-inline-c.html (C-f for `ghci`). I might get around it someday, there are no hard technical reasons for it not to work.
