### ISSUE TITLE
Please clarify Ptr usage on left side of equals.

### ISSUE THREAD

**Issue by YellowOnion** [fpco/inline-c#91]
I'm trying to use alloca to capture some values.
`
alloca $ \x -> [C.exp| $(int *x) = 3]
                  >> peek x
`
the c code should be ` *x = 3;` how do I reproduce this?

peeking x causes a me to get junk data and not 3.

**Comment by facundominguez** [comment]
Maybe
`alloca $ \x -> [C.exp| *$(int *x) = 3] >> peek x`
?

**Comment by bitonic** [comment]
What @facundominguez said -- the anti-quotation brings into scope a variable of type `int *`, and then you need to modify its value as usual. The `*` inside the anti quotation is just indicating the type, it doesn't dereference the value itself.
