### ISSUE TITLE
inline-c does not work in IHaskell (Jupyter) notebook

### ISSUE THREAD

**Issue by idontgetoutmuch** [fpco/inline-c#94]
![image](https://user-images.githubusercontent.com/1550265/61862121-3d322e80-aec5-11e9-8830-5d9f4ca45665.png)

**Comment by bitonic** [comment]
@idontgetoutmuch , how did you solve this? Presumably by setting `-fobject-code` somewhere?

**Comment by idontgetoutmuch** [comment]
I didn't solve it. I realised it was not a sensible thing to try to do.

**Comment by bitonic** [comment]
Ah, OK. For future users of IHaskell, it looks like the problem is related to not passing `-fobject-code` to ghci, see https://github.com/fpco/inline-c/tree/master/inline-c#ghci .
